import os
import time
from utils import utils
from AoC2022 import d1, d2, d3, d4, d5, d6, d7

# day 7 
print("Day 7: No Space Left On Device")
start_time = time.time()
print("- testing")
tst = d7.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2022/input/d7.txt")
signal = d7.d7(input_set)
signal.get_directories_size()
print("part1 :", signal.get_res_pt1())
print("part2 :", signal.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 6 
print("Day 6: Tuning Trouble")
start_time = time.time()
print("- testing")
tst = d6.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_file_2_str(os.getcwd() 
    + "/AoCPython/AoC2022/input/d6.txt")
signal = d6.d6(input_set)
signal.process()
print("part1 :", signal.get_res_pt1())
print("part2 :", signal.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 5 
print("Day 5: Supply Stacks")
start_time = time.time()
print("- testing")
tst = d5.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
stack_state, instr_list = inputHandler.parse_inst_from_map(os.getcwd() 
    + "/AoCPython/AoC2022/input/d5.txt")
stacks = d5.d5(stack_state, instr_list)
stacks.get_top_crates()
print("part1 :", stacks.get_res_pt1())
print("part2 :", stacks.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 4
print("Day 4: Camp Cleanup")
start_time = time.time()
print("- testing")
tst = d4.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2022/input/d4.txt")
camp = d4.d4(input_set)
camp.count_wrong_pairs()
print("part1 :", camp.get_res_pt1())
print("part2 :", camp.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 3
print("Day 3: Rucksack Reorganization")
start_time = time.time()
print("- testing")
tst = d3.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2022/input/d3.txt")
ruckacks = d3.d3(input_set)
ruckacks.get_priorities_sum()
print("part1 :", ruckacks.get_res_pt1())
print("part2 :", ruckacks.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()
# day 2
print("Day 2: Rock Paper Scissors")
start_time = time.time()
print("- testing")
tst = d2.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2022/input/d2.txt")
draws = d2.d2(input_set)
draws.get_total_score()
print("part1 :", draws.get_res_pt1())
print("part2 :", draws.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 1
print("Day 1: Calorie Counting ")
start_time = time.time()
print("- testing")
tst = d1.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2022/input/d1.txt")
elf = d1.d1(input_set)
elf.count_calories()
print("part1 :", elf.get_res_pt1())
print("part2 :", elf.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

