import os
import time
from utils import utils
from AoC2021 import d1, d2, d3, d4, d5, d6, d7, d8, d9, \
    d10, d11, d12, d13, d14, d15, d16, d17, d18, d19


# day 19
print("Day 19: Beacon Scanner")
start_time = time.time()
print("- testing")
tst = d19.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d19.txt")
probe = d19.d19(input_set)
probe.scan()
print("part1 :", probe.get_res_pt1())

print("part2 :", probe.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))
exit()

# day 18
print("Day 18: Snailfish")
start_time = time.time()
print("- testing")
tst = d18.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d18.txt")
snailfish = d18.d18(input_set)
snailfish.resolve_homework()
print("part1 :", snailfish.get_res_pt1())

print("part2 :", snailfish.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 17
print("Day 17: Trick Shot")
start_time = time.time()
print("- testing")
tst = d17.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_file_2_str(os.getcwd() 
    + "/AoCPython/AoC2021/input/d17.txt")
probe = d17.d17(input_set)
probe.launch()
print("part1 :", probe.get_res_pt1())

print("part2 :", probe.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 16
print("Day 16: Packet Decoder")
start_time = time.time()
print("- testing")
tst = d16.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_file_2_str(os.getcwd() 
    + "/AoCPython/AoC2021/input/d16.txt")
BITS = d16.d16(input_set)
BITS.sum_version_packets()
print("part1 :", BITS.get_res_pt1())

print("part2 :", BITS.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 15
print("Day 15: Chiton")
start_time = time.time()
print("- testing")
tst = d15.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d15.txt")
navigation = d15.d15(input_set)
navigation.calc_risk_path()
print("part1 :", navigation.get_res_pt1())
navigation.extend_map()
print("part2 :", navigation.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 14
print("Day 14: Extended Polymerization")
start_time = time.time()
print("- testing")
tst = d14.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d14.txt")
polymerization = d14.d14(input_set)
polymerization.extend(40)
print("part1 :", polymerization.get_res_pt1())

print("part2 :", polymerization.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 13
print("Day 13: Transparent Origami")
start_time = time.time()
print("- testing")
tst = d13.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d13.txt")
thermal_camera = d13.d13(input_set)
thermal_camera.fold_transparent_paper()
print("part1 :", thermal_camera.get_res_pt1())
print("part2 :")
thermal_camera.get_activation_code()
print("--- %s seconds ---" % (time.time() - start_time))

# day 12
print("Day 12: Passage Pathing")
start_time = time.time()
print("- testing")
tst = d12.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d12.txt")
cave = d12.d12(input_set)
cave.find_paths()
print("part1 :", cave.get_res_pt1())
cave.find_paths2()
print("part2 :", cave.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 11
print("Day 11: Dumbo Octopus ")
start_time = time.time()
print("- testing")
tst = d11.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d11.txt")
octopus = d11.d11(input_set)
octopus.simulate_flashes(100)
print("part1 :", octopus.get_res_pt1())

print("part2 :", octopus.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 10
print("Day 10: Syntax Scoring")
start_time = time.time()
print("- testing")
tst = d10.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d10.txt")
nav_system = d10.d10(input_set)
nav_system.check_syntax()
print("part1 :", nav_system.get_res_pt1())

print("part2 :", nav_system.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 9
print("Day 9: Smoke Basin")
start_time = time.time()
print("- testing")
tst = d9.test().run()

start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d9.txt")
cave = d9.d9(input_set)
cave.calc_smoke_path()
print("part1 :", cave.get_res_pt1())

print("part2 :", cave.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 8
print("Day 8: Seven Segment Search")
start_time = time.time()
print("- testing")
tst = d8.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d8.txt")
display = d8.d8(input_set)
display.output_decode()
print("part1 :", display.get_res_pt1())

print("part2 :", display.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 7
print("Day 7: The Treachery of Whales")
start_time = time.time()
print("- testing")
tst = d7.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_int_array(os.getcwd() 
    + "/AoCPython/AoC2021/input/d7.txt")
crabs = d7.d7(input_set)
crabs.get_least_fuel()
print("part1 :", crabs.get_res_pt1())

print("part2 :", crabs.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 6 
print("Day 6: Lanternfish")
start_time = time.time()
print("- testing")
tst = d6.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_int_array(os.getcwd() 
    + "/AoCPython/AoC2021/input/d6.txt")
lantern_fish = d6.d6(input_set)
lantern_fish.forecast_growth(80)
print("part1 :", lantern_fish.get_res_pt1())
lantern_fish.forecast_growth(256)
print("part2 :", lantern_fish.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 5 
print("Day 5: Hydrothermal Venture")
start_time = time.time()
print("- testing")
tst = d5.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d5.txt")
vents = d5.d5(input_set)
print("part1 :", vents.get_res_pt1())
print("part2 :", vents.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 4
print("Day 4: Giant Squid")
start_time = time.time()
print("- testing")
tst = d4.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d4.txt")
bingo_session = d4.d4(input_set)
bingo_session.start_draw()
print("part1 :", bingo_session.get_res_pt1())
print("part2 :", bingo_session.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 3
print("Day 3: Binary Diagnostic")
start_time = time.time()
print("- testing")
tst = d3.test().run()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d3.txt")
submarine = d3.d3(input_set)
submarine.calc_power_consumption()
print("part1 :", submarine.get_res_pt1())
submarine.calc_life_support()
print("part2 :", submarine.get_res_pt2())
print("--- %s seconds ---" % (time.time() - start_time))

# day 2
print("Day 2: Dive!")
start_time = time.time()
print("- testing")
tst = d2.test_d2().run_test()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_line_2_list(os.getcwd() 
    + "/AoCPython/AoC2021/input/d2.txt")
pilot = d2.d2(input_set)
pilot.calc_distance()
print("part1 :", pilot.result1)
pilot.calc_distance_with_aim()
print("part2 :", pilot.result2)
print("--- %s seconds ---" % (time.time() - start_time))

# day 1 
print("Day 1: Sonar Sweeps")
start_time = time.time()
print("- testing")
tst = d1.test_d1().run_test()
start_time = time.time()
print("- calculation")
inputHandler = utils.fileHandler()
input_set = inputHandler.parse_2_int_array(os.getcwd() 
    + "/AoCPython/AoC2021/input/d1.txt")
scanner = d1.d1(input_set)
scanner.calc_increments()
print("part1 :", scanner.result1)
print("part2 :", scanner.result2)
print("--- %s seconds ---" % (time.time() - start_time))