import time
import decimal
location_i = 2947
location_j = 3029
lim = 10000
input_var = 20151125

'''
The first code is 20151125. After that, each code is generated by taking the previous one, 
multiplying it by 252533 then keeping the remainder from 
dividing that value by 33554393.
To continue, please consult the code grid in the manual.  Enter the code at row 2978, column 3083
'''
print(time.strftime('%a, %d %b %Y %H:%M:%S GMT', time.localtime()))
for vec in range(1,lim):
    col=1
    row=vec
    #print("vec", vec)
    
    for pos in range(0,vec):
        if (row == location_i and col == location_j):
            print(vec, row,col,input_var)
            print(time.strftime('%a, %d %b %Y %H:%M:%S GMT', time.localtime()))
            exit()
        input_var=(input_var*252533)%33554393
        row-=1
        col+=1

